{{- range $i, $ingress := .Values.keycloak.ingresses }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "keycloak.fullname" $ }}-{{ $ingress.name }}
{{- with $ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "keycloak.name" $ }}
    chart: {{ template "keycloak.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
{{- with $ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
  {{- end }}
{{- end }}
  rules:
  {{- range $ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- range $ingress.paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ template "keycloak.fullname" $ }}-https
              servicePort: https
          {{- end }}
  {{- end }}
{{- end -}}
