{{- if and (not .Values.keycloak.existingSecret) .Values.keycloak.admin.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak.fullname" . }}-http
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if .Values.keycloak.admin.password }}
        {{ .Values.keycloak.existingSecretKey }}: {{ .Values.keycloak.admin.password | b64enc | quote }}
{{- else }}
        {{ .Values.keycloak.existingSecretKey }}: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
{{- end}}
